version: '2.1'

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local

services:

  traefik:
    container_name: traefik
    hostname: traefik
    build:
      context: .
      dockerfile: Dockerfile.${ARCH}
      args:
        ARCH: ${ARCH}
    image: sofwerx/traefik:${ARCH}
    restart: always
#    ports:
#      - 80:80
#      - 443:443
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      REST_PORT: "8080"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      AWS_REGION: ${AWS_REGION}
#      AWS_HOSTED_ZONE_ID: ${AWS_HOSTED_ZONE_ID}
    volumes:
      - traefik-ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

